### ISSUE TITLE
$500: Setup initial frontend test

### ISSUE THREAD

**Issue by kirkstrobeck** [tipfortip/issues#180]
This is an SSIM bounty, you must be an [official contributor](https://github.com/strobecksim/strobecksim.github.io/blob/master/Documents/Wiki/Index.md) to be compensated. 
<hr>

**Background:**

We need to get our front end testing into shape. T4T is an ionic app, which is just angular on cordova. Tests should be designed for safari and standard web browsers as those are the primary use-cases. The app is online at https://www.tipfortip.com/ionic.

**Resources:**

- We have an account with https://circleci.com

**Requirements:**

- [ ] An automated test should run upon commit that chooses a nearby location and sends a tip.

cc: @vaelinn

**Comment by kirkstrobeck** [comment]
@vaelinn can you add those test user creds to https://github.com/tipfortip/wiki/blob/master/Wiki/Index.md

**Comment by kirkstrobeck** [comment]
ETA?

**Comment by vaelinn** [comment]
Cannot progress until I get a viable test user for the stage environment. Additionally if you wish the test to run during a ci build for the code before it is deployed it will need to be running on localhost and a new test facebook app may need to be made and configured to allow requests from localhost to hit it. Beyond that there is still figuring out the difficulty of manipulating the gps coordinates in each browser via selenium, which may be different per browser. Currently difficult to give a solid eta.

**Comment by kirkstrobeck** [comment]
Hey @vaelinn can you get this pushed?

**Comment by kirkstrobeck** [comment]
Hey @vaelinn I couldn’t get the test running on the original `master`. `master` has since been merged with the latest. Can this test be fixed?

**Comment by kirkstrobeck** [comment]
```
| => protractor test/integration/conf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
F

Failures:

  1) Tip for tip Should have the correct title
   Message:
     UnknownError: unknown error: Element is not clickable at point (707, 939). Other element would receive the click: <div class="click-block"></div>
  (Session info: chrome=42.0.2311.135)
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Mac OS X 10.10.3 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 34 milliseconds
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'kirkstrobeck.local', ip: '10.0.1.122', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.6.0_65'
Session ID: c143e1c14de3e2caae5a0a8b26dd255f
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/55/rcwf6nxx41nctw5qgtln0zqw0000gn/T/.org.chromium.Chromium.jvs2hu}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=42.0.2311.135, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
   Stacktrace:
     UnknownError: unknown error: Element is not clickable at point (707, 939). Other element would receive the click: <div class="click-block"></div>
  (Session info: chrome=42.0.2311.135)
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Mac OS X 10.10.3 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 34 milliseconds
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'kirkstrobeck.local', ip: '10.0.1.122', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.6.0_65'
Session ID: c143e1c14de3e2caae5a0a8b26dd255f
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/55/rcwf6nxx41nctw5qgtln0zqw0000gn/T/.org.chromium.Chromium.jvs2hu}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=42.0.2311.135, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
    at Array.forEach (native)
Error
    at /Users/kirkstrobeck/git/tipfortip/ionic/test/integration/first-spec.js:28:127
    at Array.forEach (native)
From: Task: Asynchronous test function: it()
Error
    at [object Object].<anonymous> (/Users/kirkstrobeck/git/tipfortip/ionic/test/integration/first-spec.js:14:3)
    at Object.<anonymous> (/Users/kirkstrobeck/git/tipfortip/ionic/test/integration/first-spec.js:5:1)

Finished in 8.04 seconds
1 test, 2 assertions, 1 failure

[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
________________________________________________________________________________
| ~/git/tipfortip/ionic @ kirkstrobeck (kirkstrobeck)
| =>
```

**Comment by kirkstrobeck** [comment]
```
________________________________________________________________________________
| ~/git/tipfortip/ionic @ kirkstrobeck (kirkstrobeck)
| => protractor test/integration/conf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
F

Failures:

  1) Tip for tip Should have the correct title
   Message:
     Expected 'http://localhost:8000/ is not available' to be 'Tip for Tip'.
   Stacktrace:
     Error: Failed expectation
    at [object Object].<anonymous> (/Users/kirkstrobeck/git/tipfortip/ionic/test/integration/first-spec.js:17:7)

  2) Tip for tip Should have the correct title
   Message:
     NoSuchElementError: No element found using locator: By.xpath(".//div[contains(@class,\"button-skip-intro\")]")
   Stacktrace:
     NoSuchElementError: No element found using locator: By.xpath(".//div[contains(@class,\"button-skip-intro\")]")
    at Array.forEach (native)
Error
    at [object Object].<anonymous> (/Users/kirkstrobeck/git/tipfortip/ionic/test/integration/first-spec.js:18:71)
From: Task: Asynchronous test function: it()
Error
    at [object Object].<anonymous> (/Users/kirkstrobeck/git/tipfortip/ionic/test/integration/first-spec.js:14:3)
    at Object.<anonymous> (/Users/kirkstrobeck/git/tipfortip/ionic/test/integration/first-spec.js:5:1)

Finished in 0.629 seconds
1 test, 2 assertions, 2 failures

[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 2 test(s)
[launcher] overall: 2 failed spec(s)
[launcher] Process exited with error code 1
________________________________________________________________________________
| ~/git/tipfortip/ionic @ kirkstrobeck (kirkstrobeck)
| => protractor test/integration/conf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
F

Failures:

  1) Tip for tip Should have the correct title
   Message:
     UnknownError: unknown error: Element is not clickable at point (662, 568). Other element would receive the click: <div class="click-block"></div>
  (Session info: chrome=42.0.2311.135)
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Mac OS X 10.10.3 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 45 milliseconds
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'kirkstrobeck.local', ip: '10.0.1.122', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.6.0_65'
Session ID: 87e6e0a19ff12a422901e646ac3e7e58
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/55/rcwf6nxx41nctw5qgtln0zqw0000gn/T/.org.chromium.Chromium.CWOpeo}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=42.0.2311.135, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
   Stacktrace:
     UnknownError: unknown error: Element is not clickable at point (662, 568). Other element would receive the click: <div class="click-block"></div>
  (Session info: chrome=42.0.2311.135)
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Mac OS X 10.10.3 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 45 milliseconds
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'kirkstrobeck.local', ip: '10.0.1.122', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.6.0_65'
Session ID: 87e6e0a19ff12a422901e646ac3e7e58
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/55/rcwf6nxx41nctw5qgtln0zqw0000gn/T/.org.chromium.Chromium.CWOpeo}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=42.0.2311.135, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
    at Array.forEach (native)
Error
    at /Users/kirkstrobeck/git/tipfortip/ionic/test/integration/first-spec.js:28:127
    at Array.forEach (native)
From: Task: Asynchronous test function: it()
Error
    at [object Object].<anonymous> (/Users/kirkstrobeck/git/tipfortip/ionic/test/integration/first-spec.js:14:3)
    at Object.<anonymous> (/Users/kirkstrobeck/git/tipfortip/ionic/test/integration/first-spec.js:5:1)

Finished in 7.343 seconds
1 test, 2 assertions, 1 failure

[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
________________________________________________________________________________
| ~/git/tipfortip/ionic @ kirkstrobeck (kirkstrobeck)
| =>
```

**Comment by kirkstrobeck** [comment]
Also, note the readme changes to `ionic serve`

**Comment by HiceS** [comment]
Hey one of my friends linked me to this project and I was wondering if you guys had ever thought about using TravisCi for testing and if you guys would be open to help I would love to work on this with you. 

You can email me at: Shawn@thelogiccore.com or shawnhice@gmail.com

I would be more then happy to have lunch with you guys as well if you would feel so inclined.

Shawn Hice
-CEO of Logic Core Corporations
-Programmer at Autodesk
-Head programmer for FRC team 2471

**Comment by kirkstrobeck** [comment]
- Hey @HiceS we are currently using https://circleci.com
- Would be great to chat, thanks for reaching out
